name: build
on:
  push:
    paths:
      - .github/workflows/build.yaml
      - pkg/**
      - integration_test/**
      - go.*
      - Makefile
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.2
      - run: make test
      - run: make -C integration_test
