name: build
on:
  push:
    paths:
      - .github/workflows/build.yaml
      - pkg/**
      - integration_test/**
      - go.*
      - Makefile
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.2
        id: go
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-
      - run: make test
      # https://kubernetes-sigs.github.io/kustomize/installation/binaries/
      - run: cd $(go env GOPATH)/bin && curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
      - run: make -C integration_test
