name: go

on:
  pull_request:
    paths:
      - .github/workflows/go.yaml
      - pkg/**
      - integration_test/**
      - go.*
      - Makefile
  push:
    branches:
      - main
    paths:
      - .github/workflows/go.yaml
      - pkg/**
      - integration_test/**
      - go.*
      - Makefile

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.4
      - uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.8
          args: --timeout=3m

  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.4
      - run: go mod tidy
      - run: go fmt ./...
      - uses: int128/update-generated-files-action@v2

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.4
      - run: make test
      - run: make -C integration_test
